<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1994</name>
   <tag></tag>
   <elementGuidId>4dfd176c-da67-4879-861c-bc79693a6e77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*/text()[normalize-space(.)='1994']/parent::*</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1994&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a2f7d862-32c0-41e5-bdcc-654caf90135f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__overlay_cell dp__overlay_cell_pad</value>
      <webElementGuid>273c09f2-aac0-40ef-b983-00660f8c0447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1994</value>
      <webElementGuid>05d00941-552a-4e4f-87b1-bf812d3e7366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;&quot;]/body[1]/div[@class=&quot;dp__menu dp__menu_index dp__theme_light&quot;]/div[2]/div[@class=&quot;dp__instance_calendar&quot;]/div[1]/div[1]/div[@class=&quot;dp__month_year_row&quot;]/div[@class=&quot;dp__overlay&quot;]/div[@class=&quot;dp__overlay_container dp__container_block&quot;]/div[@class=&quot;dp__overlay_row&quot;]/div[@class=&quot;dp__overlay_col&quot;]/div[@class=&quot;dp__overlay_cell dp__overlay_cell_pad&quot;]</value>
      <webElementGuid>11685a5a-fa08-4fb2-b636-02ae624ab62b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1994']/parent::*</value>
      <webElementGuid>66912b91-1904-436c-b933-c968a36d8977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[33]/div[2]/div</value>
      <webElementGuid>6c58a921-ee86-4095-9a2f-9780a9211b39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1994' or . = '1994')]</value>
      <webElementGuid>cf49b7f3-150f-4298-b1fe-df6f3c8508ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
