<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputTanggalLahir</name>
   <tag></tag>
   <elementGuidId>f2e98545-656d-41f4-9491-5693da14dd84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.dp__pointer.dp__input_readonly.dp__input.dp__input_icon_pad.dp__input_reg.undefined</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div/div[4]/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Tanggal Lahir\*$/ >> internal:attr=[placeholder=&quot;DD/MM/YYYY&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74ca26d9-5d90-4cc4-90ee-ae61f011f0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_reg  undefined</value>
      <webElementGuid>1af5c8df-4b0c-471b-bc34-8e0480ac7180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD/MM/YYYY</value>
      <webElementGuid>d4cc0ed4-d8ee-424d-a757-ce2f4d15c5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>98becdfb-5b89-4bf9-be01-3108827f164e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;grid grid-cols-6&quot;]/div[@class=&quot;col-span-6 lg:col-span-4&quot;]/div[@class=&quot;pt-[50px] pb-[30px] lg:overflow-y-auto lg:h-screen&quot;]/div[@class=&quot;container max-w-3xl mx-auto&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 mt-5 gap-[30px]&quot;]/div[1]/div[@class=&quot;mb-5&quot;]/div[@class=&quot;dp__main dp__theme_light&quot;]/div[1]/div[@class=&quot;dp__input_wrap&quot;]/input[@class=&quot;dp__pointer dp__input_readonly dp__input dp__input_icon_pad dp__input_reg  undefined&quot;]</value>
      <webElementGuid>3f8b3ae7-54e6-48ca-bf03-997bcae71d9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>96813d2f-8e2a-43c1-a9a1-3726c856bd1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>4bd26c9a-13bb-498f-bcc8-e605d972b968</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'DD/MM/YYYY']</value>
      <webElementGuid>ef628353-e153-4228-b482-77bab15844ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
