<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadKTP</name>
   <tag></tag>
   <elementGuidId>40c6e54e-af00-4510-a78d-53b883573892</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div/div[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.px-3.py-2.border.border-primary-grey.rounded.flex.justify-between.items-center.border-primary-grey</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@name = 'uploadKtp' and @placeholder = 'Upload KTP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Upload KTPUpload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bb703576-e5d4-4661-bf92-c8c22ca72fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploadKtp</value>
      <webElementGuid>3c9453d2-d7ab-4334-9e62-71797a17fcc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Upload KTP</value>
      <webElementGuid>e61a448f-0160-4905-bca4-cde62e105579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;grid grid-cols-6&quot;]/div[@class=&quot;col-span-6 lg:col-span-4&quot;]/div[@class=&quot;pt-[50px] pb-[30px] lg:overflow-y-auto lg:h-screen&quot;]/div[@class=&quot;container max-w-3xl mx-auto&quot;]/div[2]/div[1]/form[1]/div[@class=&quot;grid grid-cols-1 lg:grid-cols-2 mt-5 gap-[30px]&quot;]/div[1]/div[@class=&quot;mb-3&quot;]/div[@class=&quot;px-3 py-2 border border-primary-grey rounded flex justify-between items-center border-primary-grey&quot;]</value>
      <webElementGuid>e9180062-ca25-4c70-af9d-a7492a503d4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div/div/div[2]/div/form/div/div/div[6]/div</value>
      <webElementGuid>94f3487f-54fb-4e3f-88b7-546f8c67f87a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload KTP*'])[1]/following::div[1]</value>
      <webElementGuid>60f7386f-5794-4ea6-b992-c856b38704c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor KTP*'])[1]/following::div[3]</value>
      <webElementGuid>45ab87dd-200d-4e73-a5da-feb2233fac89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div</value>
      <webElementGuid>73a1992b-c570-497a-97fe-54e072a7563e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Upload KTPUpload File' or . = 'Upload KTPUpload File')]</value>
      <webElementGuid>0c91aa9c-9c68-4e2f-bcbb-8d583e4efbd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
